# Ejercicio de edades e ingresos

- generar una matriz 3x3 de edades entre 20 y 50 años 
- generar una matriz 3x3 de ingresos entre 2000 y 5000 miles de pesos 
- unir la data uno a uno en una matriz de 9x2
- filtrar aquellas filas cuya edad está entre 20 y 30 años y cuyos ingresos estan entre 2000 y 5000.

In [1]:
import numpy as np

edades = np.around(np.random.uniform(
    low=20,
    high=50,
    size=(3, 3),
))

edades 

array([[36., 44., 23.],
       [39., 48., 40.],
       [42., 42., 45.]])

In [2]:
ingresos = np.around(np.random.uniform(
    low=1000,
    high=5000,
    size=(3, 3),
))

ingresos 

array([[3873., 1296., 1203.],
       [2234., 2735., 4581.],
       [2563., 4171., 2780.]])

In [3]:
edades = edades.reshape(9)
ingresos = ingresos.reshape(9)

display(
    edades,
    ingresos
)

array([36., 44., 23., 39., 48., 40., 42., 42., 45.])

array([3873., 1296., 1203., 2234., 2735., 4581., 2563., 4171., 2780.])

In [4]:
combinado = np.column_stack((edades,ingresos))

combinado

array([[  36., 3873.],
       [  44., 1296.],
       [  23., 1203.],
       [  39., 2234.],
       [  48., 2735.],
       [  40., 4581.],
       [  42., 2563.],
       [  42., 4171.],
       [  45., 2780.]])

In [5]:
booleano_edad = combinado[:,0] < 40 
booleano_edad



array([ True, False,  True,  True, False, False, False, False, False])

In [6]:
booleano_ingreso1 = combinado[:,1] > 2000 
booleano_ingreso2 = combinado[:,1] < 4000
booleano_ingreso = np.logical_and(booleano_ingreso1,booleano_ingreso2)


In [7]:
booleano_combinado = np.logical_and(booleano_edad,booleano_ingreso)

booleano_combinado


array([ True, False, False,  True, False, False, False, False, False])

In [8]:
combinado[booleano_combinado]

array([[  36., 3873.],
       [  39., 2234.]])