# Introducción a NumPy

__Numpy__ o python numérico

Vamos a importar la librería y a verificar su versión

In [1]:
import numpy as np

print(np.__version__)

1.20.2


Crear una lista de forma tradicional

In [2]:
mi_lista = [1, 2, 3, 4, 5, 6]
type(mi_lista)

list

Crear un array a partir de una lista

In [3]:
mi_array = np.array(mi_lista)

display(
    type(mi_array),
    mi_array,
    mi_array.shape,
    mi_array.ndim
)

numpy.ndarray

array([1, 2, 3, 4, 5, 6])

(6,)

1

Crear un array a partir de un dato

In [4]:
mi_array_cero = np.array(48)

display(
    type(mi_array_cero),
    mi_array_cero,
    mi_array_cero.shape,
    mi_array_cero.ndim
)

numpy.ndarray

array(48)

()

0

Crear matriz a partir de dos listas

In [5]:
mi_matriz = np.array([mi_lista, mi_lista])

display(
    type(mi_matriz),
    mi_matriz,
    mi_matriz.shape,
    mi_matriz.ndim
)

numpy.ndarray

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

(2, 6)

2

Cear un array de 3 dimensiones

In [6]:
mi_array_3d = np.array([[mi_lista, mi_lista],[mi_lista, mi_lista]])

display(
    type(mi_array_3d),
    mi_array_3d,
    mi_array_3d.shape,
    mi_array_3d.ndim
)

numpy.ndarray

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]])

(2, 2, 6)

3

Crear un array multidimensional

In [10]:
mi_array_n = np.array(mi_lista, ndmin=9)

display(
    type(mi_array_n),
    mi_array_n,
    mi_array_n.shape,
    mi_array_n.ndim
)

numpy.ndarray

array([[[[[[[[[1, 2, 3, 4, 5, 6]]]]]]]]])

(1, 1, 1, 1, 1, 1, 1, 1, 6)

9

Crear un array de ceros y otro de unos
- ones()
- zeros()

In [11]:
mis_unos = np.ones(3)
mis_ceros = np.zeros(5)

display(
    mis_unos,
    mis_ceros
)

array([1., 1., 1.])

array([0., 0., 0., 0., 0.])

Craer un array con un rango

In [12]:
mi_rango = np.arange(10)
mi_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Crear array con n valores en un rango

In [16]:
mi_linspace = np.linspace(
    start=1,
    stop=5,
    num=30,
    endpoint=True
)

mi_linspace

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

Crear array con aleatorios

In [17]:
mi_aleatorio_1 = np.random.random(size=(2,5))

mi_aleatorio_2 = np.random.uniform(
    low=1,
    high=2,
    size=(2,5)
)

mi_aleatorio_3 = np.random.normal(
    loc=1,
    scale=2,
    size=(3,5)
)

display(
    mi_aleatorio_1,
    mi_aleatorio_2,
    mi_aleatorio_3
)

array([[0.26008828, 0.54164722, 0.95599122, 0.2212895 , 0.13850621],
       [0.61591693, 0.54199315, 0.4070251 , 0.99619859, 0.2263766 ]])

array([[1.24702663, 1.92151275, 1.78326722, 1.79140048, 1.65837064],
       [1.43986601, 1.35339307, 1.11426207, 1.84733356, 1.58621601]])

array([[-3.78902164,  1.78899115, -0.25661917,  2.79213661,  2.02822524],
       [ 4.32093541,  2.59378107,  0.67757674,  3.57008919,  2.7266123 ],
       [ 2.44477159,  0.96076996,  1.99130707, -0.55244667,  2.22383246]])

Consultando elementos del array

In [18]:
display(
    mi_array,
    mi_array[0],
    mi_array[-1],
    mi_array[1:-2]
)

array([1, 2, 3, 4, 5, 6])

1

6

array([2, 3, 4])

Consultado elementos de una matriz

In [20]:
mi_cuadrada = np.array([[1,2,3],[4,5,6],[7,8,9]])

display(
    mi_cuadrada[:,0],
    mi_cuadrada[2,:],
    mi_cuadrada[:,:]
)

array([1, 4, 7])

array([7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Cambiado formas

In [21]:
display(
    mi_rango.reshape(2,5),
    mi_rango.reshape(2,5).shape,
    mi_rango.reshape(5,2),
    mi_rango.reshape(5,2).shape,
    mi_rango.shape
)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

(2, 5)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

(5, 2)

(10,)

Stack de dos arrays

In [26]:
a = np.array([1,2,3])
b = np.array([11,21,31])
ab = np.column_stack((a,b))

display(
    a,
    b,
    ab,
    ab.shape
)

array([1, 2, 3])

array([11, 21, 31])

array([[ 1, 11],
       [ 2, 21],
       [ 3, 31]])

(3, 2)

Estadísticas básicas

In [33]:
base = np.random.random(size=(15))
base *= 100

display(
    base,
    np.mean(base),
    np.median(base),
    np.var(base),
    np.std(base)
)

array([65.6593003 , 32.25176322, 32.71945214, 56.91473825, 99.4645147 ,
       73.14223394, 14.62029743, 47.19060072, 75.11082646, 63.81935261,
       21.71584714, 44.33153012, 99.54457082, 27.93137143, 41.23903211])

53.04369542610444

47.19060072207274

645.4464652961836

25.405638454803366

Operaciones aritméticas

In [34]:
array_uno = np.random.random(5)
array_dos = np.random.random(5)

display(
    array_uno,
    array_dos,
    array_uno + array_dos,
    array_uno / array_dos
)

array([0.67523753, 0.12365112, 0.98250844, 0.50744272, 0.86345162])

array([0.89958128, 0.96193456, 0.20933651, 0.26998004, 0.83268747])

array([1.5748188 , 1.08558568, 1.19184495, 0.77742276, 1.69613909])

array([0.75061314, 0.12854421, 4.69344032, 1.87955647, 1.03694562])

In [37]:
matriz_uno = np.random.random(size=(3,3))
matriz_dos = np.random.random(size=(3,3))

display(
    matriz_uno,
    matriz_dos,
    matriz_uno - matriz_dos
)

array([[0.38810671, 0.37299423, 0.24610175],
       [0.40778577, 0.09103627, 0.59216281],
       [0.10271003, 0.97544919, 0.26832675]])

array([[0.56924221, 0.7180636 , 0.16830421],
       [0.11049844, 0.71426956, 0.76188259],
       [0.446856  , 0.61444697, 0.77732218]])

array([[-0.1811355 , -0.34506937,  0.07779753],
       [ 0.29728733, -0.62323329, -0.16971978],
       [-0.34414597,  0.36100222, -0.50899543]])

arange con operadores lógicos

In [39]:
np.arange(10) > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

Selección lógica

In [41]:
arreglo = np.arange(10)
booleanos = arreglo > 3

display(
    arreglo,
    booleanos,
    arreglo[booleanos]
)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

array([4, 5, 6, 7, 8, 9])

In [42]:
booleanos_2 = arreglo < 7
booleanos_3 = np.logical_and(booleanos, booleanos_2)

display(
    booleanos_3,
    arreglo[booleanos_3]
)

array([False, False, False, False,  True,  True,  True, False, False,
       False])

array([4, 5, 6])

Iteraciones sobre arrays

In [44]:
for elemento in mi_array:
    print(elemento)

1
2
3
4
5
6


In [49]:
for elemento in matriz_uno:
    print(elemento)
    
print('')

for elemento in np.nditer(matriz_uno):
    print(elemento)

[0.38810671 0.37299423 0.24610175]
[0.40778577 0.09103627 0.59216281]
[0.10271003 0.97544919 0.26832675]

0.38810670646408474
0.372994234636141
0.24610174605569857
0.40778577201517874
0.0910362661448596
0.5921628057412328
0.10271003050882677
0.9754491898885012
0.26832674831094416
